final List<Map<String, dynamic>> postList = [
  {
    'name': 'Jean-Luc Picard',
    'username': 'captainpicard',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': true,
    'postText': 'Engage!',
  },
  {
    'name': 'Kathryn Janeway',
    'username': 'captainjaneway',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': false,
    'postText': 'Set a course for home, warp factor 9!',
  },
  {
    'name': 'Spock',
    'username': 'mrspock',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': true,
    'postText': 'Live long and prosper.',
  },
  {
    'name': 'Kira Nerys',
    'username': 'majorkira',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': true,
    'postText': 'Bajorans don\'t surrender!',
  },
  {
    'name': 'Geordi La Forge',
    'username': 'chiefengineer',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': false,
    'postText': 'I can\'t change the laws of physics!',
  },
  {
    'name': 'Data',
    'username': 'operations',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': true,
    'postText': 'Fascinating!',
  },
  {
    'name': 'Benjamin Sisko',
    'username': 'commander',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': true,
    'postText': 'It\'s a f***ing baseball!',
  },
  {
    'name': 'Worf',
    'username': 'securitychief',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': true,
    'postText': 'Today is a good day to die!',
  },
  {
    'name': 'Deanna Troi',
    'username': 'shipscounselor',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': false,
    'postText': 'I sense a great deal of confusion in you.',
  },
  {
    'name': 'Beverly Crusher',
    'username': 'chiefmedicalofficer',
    'imgUrl': 'https://picsum.photos/200',
    'isVerified': false,
    'postText': 'The health of the ship is my primary concern.',
  },
];
